stages: 
  - build
  # - test
  - deploy

Build:
  stage: build
  image: node:13.7.0 # can be upgraded, depending on your node version used
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/

# Test:
#   stage: test
#   before_script:
#     - npm install
#     - npm run test:badges

Deployment:
  stage: deploy
  image: ruby:latest
  before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
  script:
    - dpl --provider=heroku --app=$HEROKU_APPNAME --api-key=$HEROKU_APIKEY
    - export HEROKU_API_KEY=$HEROKU_APIKEY
    # - heroku run --app $HEROKU_APPNAME migrate
  environment:
    name: staging
    url: $HEROKU_APP_HOST
  only:
    - staging